### ISSUE TITLE
1.19.2 forge 无法启动

### ISSUE THREAD

**Issue by binggo999** [MCTeamPotato/MCMOD#4]
[05Aug2023 11:06:29.947] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, wangyx71, --version, 1.19.2-Forge 43.2.21, --gameDir, C:\Users\Administrator\AppData\Roaming\.minecraft\versions\1.19.2-Forge 43.2.21, --assetsDir, C:\Users\Administrator\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, 73d1a4404e8047eaa321e0f3f15e2a6f, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, 00000000402b5328, --xuid, ${auth_xuid}, --userType, Legacy, --versionType, SCL 1.1.1, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.21, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[05Aug2023 11:06:29.957] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.7 by JetBrains s.r.o.; OS Windows 10 arch amd64 version 10.0
[05Aug2023 11:06:30.757] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Administrator/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2378!/ Service=ModLauncher Env=CLIENT
[05Aug2023 11:06:32.117] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.21\fmlcore-1.19.2-43.2.21.jar is missing mods.toml file
[05Aug2023 11:06:32.127] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.21\javafmllanguage-1.19.2-43.2.21.jar is missing mods.toml file
[05Aug2023 11:06:32.128] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.21\lowcodelanguage-1.19.2-43.2.21.jar is missing mods.toml file
[05Aug2023 11:06:32.128] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.21\mclanguage-1.19.2-43.2.21.jar is missing mods.toml file
[05Aug2023 11:06:32.224] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 4 dependencies adding them to mods collection
[05Aug2023 11:06:34.327] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[05Aug2023 11:06:34.357] [main/ERROR] [mixin/]: Mixin config memorycleanermissnotoredict-forge.mixins.json does not specify "minVersion" property
[05Aug2023 11:06:34.392] [main/ERROR] [mixin/]: Mixin config yuushya.mixins.json does not specify "minVersion" property
[05Aug2023 11:06:34.402] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.2-Forge 43.2.21, --gameDir, C:\Users\Administrator\AppData\Roaming\.minecraft\versions\1.19.2-Forge 43.2.21, --assetsDir, C:\Users\Administrator\AppData\Roaming\.minecraft\assets, --uuid, 73d1a4404e8047eaa321e0f3f15e2a6f, --username, 999, --assetIndex, 1.19, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, 00000000402b5328, --xuid, ${auth_xuid}, --userType, Legacy, --versionType, SCL 1.1.1]
[05Aug2023 11:06:34.498] [main/INFO] [Rubidium/]: Loaded configuration file for Rubidium: 30 options available, 0 override(s) found
[05Aug2023 11:06:34.587] [main/WARN] [mixin/]: Reference map '${refmap_target}refmap.json' for corgilib.forge.mixins.json could not be read. If this is a development environment you can ignore this message
[05Aug2023 11:06:34.627] [main/INFO] [Sodium Extra Config/]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[05Aug2023 11:06:34.667] [main/WARN] [mixin/]: Reference map 'yuushya-1.19.2_forge-refmap.json' for yuushya.mixins.json could not be read. If this is a development environment you can ignore this message
[05Aug2023 11:06:34.737] [main/WARN] [mixin/]: Error loading class: com/simibubi/create/content/curiosities/armor/BackTankUtil (java.lang.ClassNotFoundException: com.simibubi.create.content.curiosities.armor.BackTankUtil)
[05Aug2023 11:06:34.737] [main/WARN] [mixin/]: @Mixin target com.simibubi.create.content.curiosities.armor.BackTankUtil was not found mixins.compressedcreativity.json:create.BackTankUtilMixin
[05Aug2023 11:06:34.739] [main/WARN] [mixin/]: Error loading class: com/simibubi/create/content/contraptions/fluids/pipes/BracketBlock (java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.fluids.pipes.BracketBlock)
[05Aug2023 11:06:34.739] [main/WARN] [mixin/]: @Mixin target com.simibubi.create.content.contraptions.fluids.pipes.BracketBlock was not found mixins.compressedcreativity.json:create.BracketBlockMixin
[05Aug2023 11:06:34.742] [main/WARN] [mixin/]: Error loading class: com/simibubi/create/content/curiosities/armor/CopperBacktankTileEntity (java.lang.ClassNotFoundException: com.simibubi.create.content.curiosities.armor.CopperBacktankTileEntity)
[05Aug2023 11:06:34.742] [main/WARN] [mixin/]: @Mixin target com.simibubi.create.content.curiosities.armor.CopperBacktankTileEntity was not found mixins.compressedcreativity.json:create.CopperBacktankTileEntityMixin
[05Aug2023 11:06:34.743] [main/WARN] [mixin/]: Error loading class: com/simibubi/create/content/contraptions/processing/InWorldProcessing$Type (java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.processing.InWorldProcessing$Type)
[05Aug2023 11:06:34.743] [main/WARN] [mixin/]: @Mixin target com.simibubi.create.content.contraptions.processing.InWorldProcessing$Type was not found mixins.compressedcreativity.json:create.InWorldProcessingMixin
[05Aug2023 11:06:34.747] [main/WARN] [mixin/]: Error loading class: com/simibubi/create/content/curiosities/armor/BackTankUtil (java.lang.ClassNotFoundException: com.simibubi.create.content.curiosities.armor.BackTankUtil)
[05Aug2023 11:06:34.747] [main/WARN] [mixin/]: @Mixin target com.simibubi.create.content.curiosities.armor.BackTankUtil was not found mixins.compressedcreativity.json:create.BackTankUtilMixinClient
[05Aug2023 11:06:35.317] [main/INFO] [mixin/]: Instancing error handler class com.illusivesoulworks.polymorph.mixin.IntegratedMixinPlugin
[05Aug2023 11:06:35.317] [main/FATAL] [mixin/]: Mixin prepare failed preparing HelpCommandAccessor in memorycleanermissnotoredict-forge.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'team.teampotato.minegpt.forge.forged.mixin.HelpCommandAccessor' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'team.teampotato.minegpt.forge.forged.mixin.HelpCommandAccessor' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:864) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:850) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:775) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:632) ~[?:?]
	at java.lang.Class.forName(Class.java:545) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%2399!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'team.teampotato.minegpt.forge.forged.mixin.HelpCommandAccessor' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1313) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 28 more

**Comment by binggo999** [comment]
只安装 architectury-cloth-config-MCMOD

[05Aug2023 11:24:13.367] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, wangyx71, --version, 1.19.2-Forge 43.2.0, --gameDir, C:\Users\Administrator\AppData\Roaming\.minecraft\versions\1.19.2-Forge 43.2.0, --assetsDir, C:\Users\Administrator\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, 73d1a4404e8047eaa321e0f3f15e2a6f, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, 00000000402b5328, --xuid, ${auth_xuid}, --userType, Legacy, --versionType, SCL 1.1.1, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.0, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[05Aug2023 11:24:13.372] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.7 by JetBrains s.r.o.; OS Windows 10 arch amd64 version 10.0
[05Aug2023 11:24:13.515] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Administrator/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2377!/ Service=ModLauncher Env=CLIENT
[05Aug2023 11:24:13.826] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.0\fmlcore-1.19.2-43.2.0.jar is missing mods.toml file
[05Aug2023 11:24:13.829] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.0\javafmllanguage-1.19.2-43.2.0.jar is missing mods.toml file
[05Aug2023 11:24:13.832] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.0\lowcodelanguage-1.19.2-43.2.0.jar is missing mods.toml file
[05Aug2023 11:24:13.835] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.0\mclanguage-1.19.2-43.2.0.jar is missing mods.toml file
[05Aug2023 11:24:13.904] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[05Aug2023 11:24:14.769] [main/ERROR] [mixin/]: Mixin config memorycleanermissnotoredict-forge.mixins.json does not specify "minVersion" property
[05Aug2023 11:24:14.770] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.2-Forge 43.2.0, --gameDir, C:\Users\Administrator\AppData\Roaming\.minecraft\versions\1.19.2-Forge 43.2.0, --assetsDir, C:\Users\Administrator\AppData\Roaming\.minecraft\assets, --uuid, 73d1a4404e8047eaa321e0f3f15e2a6f, --username, 123, --assetIndex, 1.19, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, 00000000402b5328, --xuid, ${auth_xuid}, --userType, Legacy, --versionType, SCL 1.1.1]
[05Aug2023 11:24:14.958] [main/FATAL] [mixin/]: Mixin prepare failed preparing HelpCommandAccessor in memorycleanermissnotoredict-forge.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'team.teampotato.minegpt.forge.forged.mixin.HelpCommandAccessor' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'team.teampotato.minegpt.forge.forged.mixin.HelpCommandAccessor' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:864) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:850) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:775) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:632) ~[?:?]
	at java.lang.Class.forName(Class.java:545) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%23108!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'team.teampotato.minegpt.forge.forged.mixin.HelpCommandAccessor' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1313) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 28 more

**Comment by QianFuv** [comment]
存在相同问题
